reddit:
  enabled: true
  subreddits:
    - chicago
  client_id: LA3bPvcz7IEJKqyYFqJRwA
  client_secret: k0aaHoWO8st-_uj1Yr625tuAH2T9UA
  user_agent: media-monitor-bot/0.1 by /u/mmchicago

youtube:
  enabled: true
  api_key: AIzaSyAVUHD1nzkuBobHG57ltqi10n1ecyqiG1E
  channels:
    - UCOZnlN6M4FVIm0_fbrEjUYQ

smtp:
  enabled: true
  server: smtp.fastmail.com
  port: 465
  username: michael@morowitz.com
  password: 3x6e92356e998w99
  from: mediamonitor@morowitz.com
  to:
    - michael@morowitz.com
  subject: "Integration Test - Media Monitor Report"